// frontend_react/src/Components/Login.js
import React, {useState} from "react";
import {useLocation, useNavigate} from 'react-router-dom'
import {login} from "../utils/json-requests";
import {log} from "../utils/logger";
import "../styles/colors.css"
import "../styles/login.css"



const Login = props => {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [showForgot, setShowForgot] = useState(false)
    const [emailForgot, setEmailForgot] = useState("")
    let from =  useLocation().state?.from?.pathname || "/";
    const navigate = useNavigate()

    const handleChangeEmail = (event) => {
        setEmail(event.target.value);
    }

    const handleChangePassword = (event) => {
        setPassword(event.target.value);
    }

    const handleChangeEmailForgot = (event) => {
        setEmailForgot(event.target.value);
    }


    async function handleSubmitLogin(event) {
        log("handle login submit")
        event.preventDefault();
        let credentials = JSON.stringify({
            "email": email,
            "password": password
        });
        log(credentials)
        // post, if any errors, show them
        let output = await login("/login", credentials);
        console.log(output)
        if (output.success) {
            props.setIsLoggedIn(true)
            // navigate to original path or '/'
            navigate(from, { replace: true });
        }
    }

    async function handleSubmitForgot(event) {
        log("handle forgot submit")
        event.preventDefault();
        let credentials = JSON.stringify({
            "email": email,
        });
        log(credentials)
        // post, if any errors, show them
        let output = await login("/forgot", credentials);
        console.log(output)
        if (output.success) {
        }
        setShowForgot(false)
    }

    return (
        <div className="body">
            <section className="body-left">
                <img src={process.env.PUBLIC_URL + "/assets/0-1-osoc-full-2.png"} alt="osoc-logo"/>
            </section>

            <section className="body-right">
                <div className="login-container">
                    <p className="welcome-message">Please provide login credentials to proceed</p>
                    <div className="login-form">
                        <form onSubmit={handleSubmitLogin}>
                            <input type="email" name="email" value={email} onChange={handleChangeEmail} placeholder="Email address"/>
                            <input type="password" name="password" value={password} onChange={handleChangePassword} placeholder="Password"/>
                            <input className="submit" type="submit" name="submit" value="Login"/>
                        </form>
                    </div>
                    {(!showForgot)? (
                        <button className="submit" onClick={() => {setEmailForgot(email); setShowForgot(true);}} >Forgot your password?</button>
                        ):
                        (
                        <div>
                            <p className="welcome-message">Please provide your email address to proceed</p>
                            <form onSubmit={handleSubmitForgot}>
                                <input type="email" name="email" value={emailForgot} onChange={handleChangeEmailForgot} placeholder="Email address"/>
                                <input className="submit" type="submit" name="submit" value="Reset my password"/>
                            </form>
                        </div>
                        )}
                </div>
            </section>
        </div>
    )
}



export default Login

// frontend/src/views/Login.vue
<script >
import {mapActions } from 'vuex';
export default {
  name: 'Login',
  data() {
    return {
      user: {
        email: '',
        password: ''
      }
    }
  },
  methods:{
    ...mapActions(['logIn']),
    async loginButton() {
      if (this.user.email !== "" && this.user.password !== "") {
        await this.logIn(this.user);
      }
    }
  }
}


</script>

<template>

  <div class="body">

    <section class="body-left">
      <img src="../assets/images/logo-osoc-color.svg" alt="osoc-logo">
    </section>

    <section class="body-right">

      <div class="login-container">
        <p class="welcome-message">Please provide login credentials to proceed</p>
        <div class="login-form">
          <input v-model="user.email" type="email" name="" placeholder="Email address">
          <input v-model="user.password" type="password" name="" placeholder="Password">
          <input class="submit" v-on:click=loginButton type="submit" name="" value="Login">
        </div>
          <router-link :to="{name: 'Forgot'}"><p class="forgot-text">Forgot your password?</p></router-link>
        <div class="forgot">

        </div>
      </div>
    </section>
  </div>

</template>

<style scoped>
@import "../assets/styles/base.css";
@import "../assets/styles/login.css";
</style>
